version: "3"

networks:
  gitea:
    external: false

services:
  server:
    image: gitea/gitea:latest
    env_file: 
      - /Volumes/WD-Passport-500GB/persistent_volume/config/gitea/gitea.env
    restart: always
    networks:
      - gitea
    volumes:
      - '/Volumes/WD-Passport-500GB/persistent_volume/data/runtime/gitea/data/:/data'
    ports:
      - "3000:3000"
      - "222:22"
    depends_on:
      - db

  db:
    image: postgres:11.2-alpine
    restart: always
    env_file:
      - /Volumes/WD-Passport-500GB/persistent_volume/config/gitea/gitea.env
    networks:
      - gitea
    volumes:
      - '/Volumes/WD-Passport-500GB/persistent_volume/data/runtime/gitea/postgres/:/var/lib/postgresql/data'